[package]
name = "seeker"
version = "0.1.0"
edition = "2024"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
strip = "symbols"    


[dependencies]
libc = "0.2.177"
pcap = "2.3.0"
rand = "0.8.5"
clap = { version = "4.5", features = ["derive"] }
