[package]
name = "seeker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }   # for argument parsing
ipnetwork = "0.21.1"    # for ip range
default-net = "0.22"    # for network interface info
pcap = "2.3.0"          # for sniffer
pnet = "0.35.0"         # for packet crafting
socket2 = "0.6.0"       # *  *  *
anyhow = "1.0.75"       # *  *  *
rand = "0.8.5"          # for random numbers